# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19p5HUSBh8BQfMsZ_Q4qLHxjdhXZizZrg
"""

def salvar_contatos(lista):
    arquivo = open("contatos.txt", "w")

    for contato in lista:  
        arquivo.write("{}#{}#{}\n".format(contato['nome'], contato['email'],contato['tel']))
    
    arquivo.close()

def carregar_contatos():
    lista = []

    try:
          arquivo = open("contatos.txt","r")
          for linha in arquivo.readlines():
              coluna = linha.strip().split("#")
              contato = {
                "email": coluna[1],
                "nome": coluna [0],
                "tel": coluna [2]
               }
              lista.append(contato)
          arquivo.close()
    except FileNotFoundError: 
       pass

    return lista


def existe_contato(lista, email):

  if len(lista) > 0:
      for contato in lista:
        if contato['email'] == email:
          return True
      return False 

def adicionar(lista):
  
  while True:
    email = input("Digite o e-mail do contato: ")

    if not existe_contato(lista, email):
        break
    else:
      print("Esse e-mail já foi utilizado.")
      print("Por favor, tente um novo e-mail")

  contato = {
        "email": email,
        "nome": input("Digite o nome"),
        "tel": input("Digite o telefone")
    }

  lista.append(contato)

  print("O contato {} foi cadastrado com sucesso!\n" . format(contato['nome']))  



def alterar(lista):
    print("== Alterar Contato ==")
    if len(lista) > 0:
          email = input("Digite o email do contato a ser alterado:")
          if existe_contato(lista, email):
              for contato in lista:
                if contato['email'] == email:
                   print("Nome: {}".format(contato['nome']))
                   print("Email: {}".format(contato['email']))
                   print("Telefone: {}".format(contato["tel"]))
                   print("===========================================\n")
                   
                   contato['nome'] = input("digite o novo nome do contato:")
                   contato['tel'] = input("Digite o novo telefone do contato")
                   break
          
          else:  
              print("Não existe contato cadastrado no sistema com o email {}.".format(email))

    else:
        print("Não existe nenhum contato cadastrado no sistema.\n")
  
    

def excluir(lista):
  print("== Exluir Contato ==")
  if len(lista) > 0:
          email = input("Digite o email do contato a ser excluido:")
          if existe_contato(lista, email):
              for i, contato in enumerate(lista):
                if contato['email'] == email:
                   print("Nome: {}".format(contato['nome']))
                   print("Email: {}".format(contato['email']))
                   print("Telefone: {}".format(contato["tel"]))
                   print("===========================================\n")

                   del lista[i]

                   print("O contato foi apagado com sucesso")
                   break

          else:  
              print("Não existe contato cadastrado no sistema com o email {}.".format(email))

  else:
        print("Não existe nenhum contato cadastrado no sistema.\n")
  

def buscar(lista):
    print("== Buscar Contato ==")
    if len(lista) > 0:

          email = input("Digite o email do contato a ser encontrado:")
          if existe_contato(lista, email):
              for contato in lista:
                if contato['email'] == email:
                   print("Nome: {}".format(contato['nome']))
                   print("Email: {}".format(contato['email']))
                   print("Telefone: {}".format(contato["tel"]))
                   print("===========================================\n")
                   break
          else:  
              print("Não existe contato cadastrado no sistema com o email {}.".format(email))

    else:
        print("Não existe nenhum contato cadastrado no sistema.\n")
  

def listar(lista):
    print("== Listar Contatos ==")
    if len(lista) > 0:
        for i, contato in enumerate(lista):
            print("Contato {}:".format(i+1))
            print("\tNome: {}".format(contato['nome']))
            print("\tEmail: {}".format(contato['email']))
            print("\tTelefone: {}".format(contato["tel"]))
            print("===========================================")

        print("Quantidade de contatos: {}\n".format(len(lista)))

    else:
      print("Não existe nenhum contato cadastrado no sistema.\n")       

  

def principal():

    lista = carregar_contatos()

    while True:    
        print(" === Agenda Telefonica ===")
        print(" 1 - Adcionar contato ")
        print(" 2 - Alterar contato ")
        print(" 3 - Excluir contato ")
        print(" 4 - Buscar contato ")
        print(" 5 - Listar contato ")
        print(" 6 - Sair ")
        opção = int(input("> "))

        if opção == 1:
          adicionar(lista)
          salvar_contatos(lista)
        elif opção == 2:
          alterar(lista)
          salvar_contatos(lista)
        elif opção == 3:
          excluir(lista)
          salvar_contatos(lista)
        elif opção == 4:
          buscar(lista)
        elif opção == 5:
          listar(lista)
        elif opção == 6:
          print("Saindo do programa...")
          break
        else:
          print("Opção inválida. Por favor, tente novamente")

principal()

